### ISSUE TITLE
couchapp clone still work for Sofa?

### ISSUE THREAD

**Issue by Kenzku** [jchris/sofa#17]
Hi, does this still work?
couchapp clone http://jchrisa.net/drl/_design/sofa

firstly, I could not open http://jchrisa.net;
secondly, if I run that command, I will receive loads errors:

2012-06-11 14:32:53 [CRITICAL] unknown error [socket.error: [Errno 60] Operation timed out]

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/dispatch.py", line 48, in dispatch
    return _dispatch(args)
  File "/Library/Python/2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/dispatch.py", line 94, in _dispatch
    return fun(conf, _args, *_opts)
  File "/Library/Python/2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/commands.py", line 208, in clone
    clone_app.clone(source, dest, rev=opts.get('rev'))
  File "/Library/Python/2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/clone_app.py", line 52, in clone
    doc = db.open_doc("_design/%s" % docid)
  File "/Library/Python/2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/client.py", line 260, in open_doc
    resp = self.res.get(escape_docid(docid), *_params)
  File "/Library/Python/2.7/site-packages/restkit-4.1.3-py2.7.egg/restkit/resource.py", line 114, in get
    params_dict=params_dict, *_params)
  File "/Library/Python/2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/client.py", line 143, in request
    raise RequestFailed("unknown error [%s]" % str(e))
RequestFailed: unknown error [socket.error: [Errno 60] Operation timed out]

**Comment by thomasbreitbach** [comment]
you can grab the code from github. http://jchrisa.net/ seems to be down... (Operation timed out)

this worked for me on ubuntu 12.04:
git clone git://github.com/jchris/sofa.git
cd ~/sofa
couchapp push . http://127.0.0.1:5984/sofadb

or

couchapp clone https://github.com/jchris/sofa.git (?)
